export const SET_PACKAGE_HOME_BANNERS = 'SET_PACKAGE_HOME_BANNERS';
export const SET_PACKAGE_HOME_ALBUMS = 'SET_PACKAGE_HOME_ALBUMS';
export const CONCAT_PACKAGE_HOME_ALBUMS = 'CONCAT_PACKAGE_HOME_ALBUMS';
